### PR TITLE
additional routes for projects

### PR DESCRIPTION
**Pull request by rentzso**
- route to purge a project
- route to get all acquisitions in a project

### CODE REVIEW

**Comment by constellates** [comment]
I'm getting a 500 error when trying to request the new project acquisitions endpoint. Here's the stack trace.

```
Traceback (most recent call last):
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/myuser/Projects/crn/bids-core/api/api.py", line 157, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/myuser/Projects/crn/bids-core/api/base.py", line 128, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/myuser/Projects/crn/bids-core/runtime/lib/python2.7/site-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/myuser/Projects/crn/bids-core/api/handlers/containerhandler.py", line 163, in get_acquisitions_in_project
    results = permchecker(openfmriutils.acquisitions_in_project)('GET', _id)
  File "/Users/myuser/Projects/crn/bids-core/api/auth/containerauth.py", line 41, in f
    return exec_op(method, _id=_id, payload=payload)
TypeError: acquisitions_in_project() got an unexpected keyword argument '_id'
```

**Comment by rentzso** [comment]
I just pushed the fix for the issue. Sorry about it.

**Comment by constellates** [comment]
That fixed that issue. Now the new project acquisitions endpoint isn't working for snapshots. I'm getting a 404. Is this the correct url structure?

```
http://localhost:8110/api/snapshots/projects/<snapshot ID>/acquisitions
```

So far the purge deletion is working for both projects and snapshots.

**Comment by rentzso** [comment]
@constellates I have pushed a new commit that include also that route for acquisitions in a project snapshot. Could you test it?

**Comment by constellates** [comment]
It's working so far. I'll try to wrap up testing today and merge this and close out the related issues.

Thanks for the help. These changes have been really nice simple solutions to a couple big performance pain points we've had for a while.

**Pull request merged**
